### ISSUE TITLE
[Wiki] Eu sei como programar, mas não sei o que programar

### ISSUE THREAD

**Issue by gnramos** [gnramos/CIC-APC#8]
- Fazer tradução de pontos principais do texto
- Incluir comentários relevantes
- incluir links?

**Comment by wladimirgramacho** [comment]
Vou dar uma olhada e ver no que posso ajudar.

**Comment by GTaumaturgo** [comment]
Publiquei lá. Falta arrumar um pouco a formatação e colocar links.
